In [6]:
import pandas as pd
import pyreadstat

In [7]:
# File names (SPSS format)
ivs_path = "../data/Integrated_values_surveys_1981-2022.sav"

In [8]:
# Load data
ivs_data, ivs_meta = pyreadstat.read_sav(ivs_path, encoding='latin1')
ivs_df = pd.DataFrame(ivs_data)

In [9]:
ivs_df.head()

,studyno,version,doi,stdyno_w,versn_w,S001,s002,S002EVS,s002vs,S003,...,Y022B,Y022C,Y023,Y023A,Y023B,Y023C,Y024,Y024A,Y024B,Y024C
0,4001.0,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,1562.0,WVS7 v.5.0,2.0,7.0,NaN,7.0,20.0,...,0.66,0.66,0.296296,0.333333,0.111111,0.444444,0.000,0.00,0.0,0.000
1,4001.0,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,1562.0,WVS7 v.5.0,2.0,7.0,NaN,7.0,20.0,...,0.66,0.66,0.888889,0.888889,0.888889,0.888889,0.500,1.00,0.0,0.500
2,4001.0,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,1562.0,WVS7 v.5.0,2.0,7.0,NaN,7.0,20.0,...,0.66,0.66,0.666667,1.000000,0.444444,0.555556,0.415,0.33,0.5,0.415
3,4001.0,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,1562.0,WVS7 v.5.0,2.0,7.0,NaN,7.0,20.0,...,1.00,1.00,0.592593,0.555556,0.333333,0.888889,0.415,0.33,0.5,0.415
4,4001.0,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,1562.0,WVS7 v.5.0,2.0,7.0,NaN,7.0,20.0,...,0.66,0.66,0.629630,0.777778,0.444444,0.666667,0.250,0.00,0.5,0.250

In [10]:
# save ivs_df to pkl
ivs_df.to_pickle("../data/ivs_df.pkl")

In [11]:
# Extract metadata details
variable_names = ivs_meta.column_names
variable_labels = ivs_meta.column_labels
variable_types = [ivs_meta.readstat_variable_types[var] for var in variable_names]
variable_measure = [ivs_meta.variable_measure.get(var, 'None') for var in variable_names]
variable_alignment = [ivs_meta.variable_alignment.get(var, 'None') for var in variable_names]
variable_display_width = [ivs_meta.variable_display_width.get(var, 'None') for var in variable_names]
missing_values = [ivs_meta.missing_user_values.get(var, 'None') for var in variable_names]

# Replace "Double" with "Numeric" in Type
variable_types = ['Numeric' if vtype == 'double' else vtype.capitalize() for vtype in variable_types]

# Create a DataFrame to mimic the SPSS Variable View
variable_view = pd.DataFrame({
    'Name': variable_names,
    'Type': variable_types,
    'Width': variable_display_width,
    'Label': variable_labels,
    'Missing': missing_values,
    'Measure': variable_measure,
    'Align': variable_alignment
})

variable_view

,Name,Type,Width,Label,Missing,Measure,Align
0,studyno,Numeric,10,Study number,None,nominal,unknown
1,version,String,26,Version,None,nominal,unknown
2,doi,String,26,Digital Object Identifier,None,nominal,unknown
3,stdyno_w,Numeric,10,Study number (wave),None,nominal,unknown
4,versn_w,String,90,Version (wave),None,nominal,unknown
...,...,...,...,...,...,...,...
833,Y023C,Numeric,8,DIVORLIB- Welzel choice-3: Divorce acceptable,None,scale,unknown
834,Y024,Numeric,8,VOICE.- Welzel voice sub-index,None,scale,unknown
835,Y024A,Numeric,8,VOICE1- Welzel voice-1,None,scale,unknown
836,Y024B,Numeric,8,VOICE2- Welzel voice-2,None,scale,unknown
837,Y024C,Numeric,8,VOI2_00- Welzel voice-3 (auxiliary),None,scale,unknown

In [12]:
# save variable_view to pkl
variable_view.to_pickle("../data/variable_view.pkl")